import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import { CTIDRecord } from '../ctid/ctid-types.js';
import { generateChangelog, generateCTIDIndex, ChangelogEntry } from './changelog-generator.js';
import { generateVersionPage, VersionSnapshot } from './version-snapshot.js';
import { WikiGitClient } from './wiki-git-client.js';

export interface WikiGeneratorOptions {
  owner: string;
  repo: string;
  version: string;
  dryRun?: boolean;
  cwd?: string;
}

export class WikiGenerator {
  private options: Required<WikiGeneratorOptions>;
  private client: WikiGitClient;

  constructor(options: WikiGeneratorOptions) {
    this.options = {
      dryRun: true,
      cwd: process.cwd(),
      ...options,
    };
    this.client = new WikiGitClient(options.owner, options.repo, this.options.dryRun);
  }

  private writeLocal(relativePath: string, content: string): string {
    const fullPath = resolve(this.options.cwd, 'docs/wiki', relativePath);
    const dir = fullPath.substring(0, fullPath.lastIndexOf('/') === -1 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, content, 'utf-8');
    return fullPath;
  }

  generateHome(projectName: string, description: string): string {
    const content = [
      `# ${projectName}`,
      '',
      description,
      '',
      `## Navigation`,
      `- [Changelog](Changelog)`,
      `- [Architecture](Architecture/Overview)`,
      `- [CTID Index](Cognitive/CTID-Index)`,
      '',
      `*Generated by AGS v${this.options.version} on ${new Date().toISOString()}*`,
    ].join('\n');

    const path = this.writeLocal('Home.md', content);
    console.log(`[wiki] Generated Home.md -> ${path}`);
    return content;
  }

  generateChangelog(entries: ChangelogEntry[]): string {
    const content = generateChangelog(entries);
    const path = this.writeLocal('Changelog.md', content);
    console.log(`[wiki] Generated Changelog.md -> ${path}`);
    return content;
  }

  generateVersionPage(snapshot: VersionSnapshot): string {
    const content = generateVersionPage(snapshot);
    const path = this.writeLocal(`Versions/v${snapshot.version}.md`, content);
    console.log(`[wiki] Generated version page -> ${path}`);
    return content;
  }

  generateCTIDIndex(records: CTIDRecord[]): string {
    const content = generateCTIDIndex(records);
    const path = this.writeLocal('Cognitive/CTID-Index.md', content);
    console.log(`[wiki] Generated CTID index -> ${path}`);
    return content;
  }

  generateArchitectureOverview(overview: string): string {
    const path = this.writeLocal('Architecture/Overview.md', overview);
    console.log(`[wiki] Generated Architecture/Overview.md -> ${path}`);
    return overview;
  }

  async generateAll(opts: {
    projectName: string;
    description: string;
    changelogEntries: ChangelogEntry[];
    ctidRecords: CTIDRecord[];
    snapshot: VersionSnapshot;
    architectureOverview?: string;
  }): Promise<void> {
    this.generateHome(opts.projectName, opts.description);
    this.generateChangelog(opts.changelogEntries);
    this.generateVersionPage(opts.snapshot);
    this.generateCTIDIndex(opts.ctidRecords);
    if (opts.architectureOverview) {
      this.generateArchitectureOverview(opts.architectureOverview);
    }

    await this.client.push([]);
  }
}
